# Generated by Django 5.0.2 on 2024-04-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('size', models.CharField(max_length=250, verbose_name='Название')),
                ('materials', models.CharField(max_length=250, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Цена')),
                ('discount_percentage', models.IntegerField(verbose_name='Процент скидки')),
                ('in_stock', models.BooleanField(verbose_name='В наличии')),
                ('description', models.TextField(verbose_name='Описание')),
                ('date', models.DateTimeField(verbose_name='Дата публикации')),
            ],
        ),
    ]
