# Generated by Django 5.0.2 on 2024-04-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='flower',
            name='discount_percentage',
            field=models.IntegerField(default=0, verbose_name='Процент скидки'),
        ),
        migrations.AlterField(
            model_name='flower',
            name='in_stock',
            field=models.BooleanField(default=True, verbose_name='В наличии'),
        ),
        migrations.AlterField(
            model_name='flower',
            name='materials',
            field=models.CharField(max_length=250, verbose_name='Материалы'),
        ),
        migrations.AlterField(
            model_name='flower',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='flower',
            name='size',
            field=models.CharField(max_length=250, verbose_name='Размер'),
        ),
    ]
