# Generated by Django 5.0.2 on 2024-04-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0004_flower_category_alter_image_flower'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='is_promotion',
            field=models.BooleanField(default=False, verbose_name='В акции'),
        ),
        migrations.AddField(
            model_name='flower',
            name='is_seasonal',
            field=models.BooleanField(default=False, verbose_name='В акции'),
        ),
    ]
